spring.datasource.url: jdbc:mysql://localhost/booklib?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: 12345678
spring.jpa.hibernate.ddl-auto: none
someParameter: 5463